title: Off the Beaten Track (with Isomer)
url: https://www.isomer.gov.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#46211a"
  secondary-color: "#a43820"
  media-colors:
    - title: media-color-one
      color: "#f1d3b2"
    - title: media-color-two
      color: "#2a3132"
    - title: media-color-three
      color: "#763626"
    - title: media-color-four
      color: "#90afc5"
    - title: media-color-five
      color: "#d09683"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d2x3wbgn8n129r.amplifyapp.com
prod: https://master.d2xayunrqqfdop.amplifyapp.com
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
resources_name: other-resources
